version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8550:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: HMaa.25
      DB_NAME: hmaa_controle_papel
    command: tail -f /dev/null
  db:
    image: mysql:8.0
    container_name: hmaa-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: HMaa.25
      MYSQL_DATABASE: hmaa_controle_papel
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql:
    name: hmaa-papel_mysql