version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: hmaa-papel-frontend
    ports:
      - "8550:80"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: hmaa-papel-backend
    restart: unless-stopped
    depends_on:
      db: # <-- MUDANÇA IMPORTANTE ABAIXO
        condition: service_healthy # O backend só inicia DEPOIS que o DB estiver "saudável"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=HMaa.25
      - DB_NAME=hmaa_controle_papel
    
  db:
    build: ./mysql # <-- MUDANÇA: Construir a imagem do MySQL a partir da nossa pasta
    container_name: hmaa-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=HMaa.25
      - MYSQL_DATABASE=hmaa_controle_papel
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: # <-- MUDANÇA: Adiciona uma verificação de saúde
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    name: hmaa-papel_mysql_data