# nginx/Dockerfile

# Comece com a imagem oficial do Nginx
FROM nginx:1.25-alpine

# Copie nosso arquivo de configuração local para o local correto dentro da imagem
COPY default.conf /etc/nginx/conf.d/default.conf